site_name: Caravel
site_logo: img/logo_caravel_dark.svg
site_url: http://code.databio.org/caravel/
repo_url: http://github.com/databio/caravel
theme: databio

nav:
  - Getting started:
    - Introduction: README.md

  - How-to Guides:
    - How to configure: configure.md

  - Reference:
    - Features: features.md
    - Usage: usage.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

navbar:
  left:
  # - text: Episb web app
  #   icon: fa-play
  #   href: http://episb.org
  # - text: Documentation
  #   icon: fa-pencil
  #   href: reference/index.html
  - text: GitHub
    icon: fa-github fa-lg
    href: https://github.com/databio/episb-hub
  right:
  - text: Databio.org
    href: http://databio.org
  - text: Software & Data
    href: http://databio.org/software/